/*.$file${.::calc1.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: calc1_sub1.qm
* File:  ${.::calc1.c}
*
* This code has been generated by QM 4.6.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-EVAL
* Issued to   : Institution or an individual evaluating the QP/C framework
* Framework(s): qpc
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* https://www.state-machine.com/licensing/#RequestForm
*/
/*.$endhead${.::calc1.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"   /* QP/C */
#include "bsp.h"   /* board support package */
#include "calc1.h" /* application */

Q_DEFINE_THIS_FILE

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.5.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${SMs::the_calc} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::the_calc} ........................................................*/
QHsm * const the_calc = &Calc_inst.super;
/*.$enddef${SMs::the_calc} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${SMs::Calc_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::Calc_ctor} .......................................................*/
void Calc_ctor(void) {
    Calc *me = &Calc_inst;
    QMsm_ctor(&me->super, Q_STATE_CAST(&Calc_initial));
}
/*.$enddef${SMs::Calc_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*.$define1${SMs::Calc} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::Calc} ............................................................*/
Calc Calc_inst;

/* guard function to evaluate the current expression
* taking into account the precedence of operands.
* return: true if evaluation successfull
* false when error encountered
*/
/*.${SMs::Calc::eval} ......................................................*/
bool Calc_eval(Calc * const me, double op, uint8_t oper) {
    double result;
    if ((oper == KEY_NULL) || (oper == KEY_PLUS) || (oper == KEY_MINUS)) {
        switch (me->oper2) {
            case KEY_MULT: {
                me->op2 *= op;
                break;
            }
            case KEY_DIVIDE: {
                if ((-1e-30 < op) && (op < 1e-30)) {
                    BSP_display_error(" Error 0 "); /* divide by zero */
                    return false;
                }
                me->op2 /= op;
                break;
             }
             default: { /* no op2 yet */
                me->op2 = op;
                me->oper2 = oper;
                break;
             }
        }
        switch (me->oper1) {
            case KEY_PLUS: {
                me->op1 += me->op2;
                break;
            }
            case KEY_MINUS: {
                me->op1 -= me->op2;
                break;
            }
            case KEY_MULT: {
                me->op1 *= me->op2;
                break;
            }
            case KEY_DIVIDE: {
                if ((-1e-30 < me->op2) && (me->op2 < 1e-30)) {
                    BSP_display_error(" Error 0 "); /* divide by zero */
                    return false;
                }
                me->op1 /= me->op2;
                break;
            }
            default: {
                Q_ERROR();
                break;
            }
        }
        me->oper1 = oper;
        me->oper2 = KEY_NULL;
        result = me->op1;
    }
    else { /* (oper == KEY_MULT) || (oper == KEY_DIV) */
        switch (me->oper2) {
            case KEY_MULT: {
                me->op2 *= op;
                break;
            }
            case KEY_DIVIDE: {
                if ((-1e-30 < op) && (op < 1e-30)) {
                    BSP_display_error(" Error 0 "); /* divide by zero */
                    return false;
                }
                me->op2 /= op;
                break;
            }
            default: { /* oper2 not provided yet */
                me->op2 = op;
                break;
            }
        }
        me->oper2 = oper;
        result = me->op2;
    }

    if ((result < -99999999.0) || (99999999.0 < result)) {
        BSP_display_error(" Error 1 "); /* out of range */
        return false;
    }
    if ((-0.0000001 < result) && (result < 0.0000001)) {
        result = 0.0;
    }
    BSP_display(result);

    return true;
}

/*.$enddef${SMs::Calc} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define1${SMs::Calc::SM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::Calc::SM} ........................................................*/
QState Calc_initial(Calc * const me, QEvt const * const e) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &Calc_on_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_on_e), /* entry */
            Q_ACTION_CAST(&Calc_on_i), /* initial tran. */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*.${SMs::Calc::SM::initial} */
    (void)e; /* unused parameter */
    return QM_TRAN_INIT(&tatbl_);
}
/*.$enddef${SMs::Calc::SM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*.$define${SMs::Calc::SM::on} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::Calc::SM::on} ....................................................*/
QMState const Calc_on_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&Calc_on),
    Q_ACTION_CAST(&Calc_on_e),
    Q_ACTION_CAST(&Calc_on_x),
    Q_ACTION_CAST(&Calc_on_i)
};
/*.${SMs::Calc::SM::on} */
QState Calc_on_e(Calc * const me) {
    BSP_message("on-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_on_s);
}
/*.${SMs::Calc::SM::on} */
QState Calc_on_x(Calc * const me) {
    BSP_message("on-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_on_s);
}
/*.${SMs::Calc::SM::on::initial} */
QState Calc_on_i(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &Calc_ready_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_ready_e), /* entry */
            Q_ACTION_CAST(&Calc_ready_i), /* initial tran. */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*.${SMs::Calc::SM::on::initial} */
    BSP_message("on-INIT;");
    BSP_clear();
    return QM_TRAN_INIT(&tatbl_);
}
/*.${SMs::Calc::SM::on} */
QState Calc_on(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::on::C} */
        case C_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_on_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_on_x), /* exit */
                    Q_ACTION_CAST(&Calc_on_e), /* entry */
                    Q_ACTION_CAST(&Calc_on_i), /* initial tran. */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::OFF} */
        case OFF_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_final_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_on_x), /* exit */
                    Q_ACTION_CAST(&Calc_final_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

/* Error state after evaluation of an expression.
This state can be exited only throgh the inherited C (Clear) event.
*/
/*.${SMs::Calc::SM::on::error} .............................................*/
QMState const Calc_error_s = {
    &Calc_on_s, /* superstate */
    Q_STATE_CAST(&Calc_error),
    Q_ACTION_CAST(&Calc_error_e),
    Q_ACTION_CAST(&Calc_error_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::on::error} */
QState Calc_error_e(Calc * const me) {
    BSP_message("error-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_error_s);
}
/*.${SMs::Calc::SM::on::error} */
QState Calc_error_x(Calc * const me) {
    BSP_message("error-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_error_s);
}
/*.${SMs::Calc::SM::on::error} */
QState Calc_error(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.${SMs::Calc::SM::on::ready} .............................................*/
QMState const Calc_ready_s = {
    &Calc_on_s, /* superstate */
    Q_STATE_CAST(&Calc_ready),
    Q_ACTION_CAST(&Calc_ready_e),
    Q_ACTION_CAST(&Calc_ready_x),
    Q_ACTION_CAST(&Calc_ready_i)
};
/*.${SMs::Calc::SM::on::ready} */
QState Calc_ready_e(Calc * const me) {
    BSP_message("ready-ENTRY;");
    me->oper2 = KEY_NULL;
    return QM_ENTRY(&Calc_ready_s);
}
/*.${SMs::Calc::SM::on::ready} */
QState Calc_ready_x(Calc * const me) {
    BSP_message("ready-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_ready_s);
}
/*.${SMs::Calc::SM::on::ready::initial} */
QState Calc_ready_i(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &Calc_begin_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_begin_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    /*.${SMs::Calc::SM::on::ready::initial} */
    BSP_message("ready-INIT;");
    return QM_TRAN_INIT(&tatbl_);
}
/*.${SMs::Calc::SM::on::ready} */
QState Calc_ready(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::on::ready::DIGIT_0} */
        case DIGIT_0_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_CAST(&Calc_ready_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand1_e), /* entry */
                    Q_ACTION_CAST(&Calc_operand_zero_ep), /* EP */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_clear();
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::ready::DIGIT_1_9} */
        case DIGIT_1_9_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_CAST(&Calc_ready_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand1_e), /* entry */
                    Q_ACTION_CAST(&Calc_operand_intgr_ep), /* EP */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_clear();
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::ready::POINT} */
        case POINT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_CAST(&Calc_ready_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand1_e), /* entry */
                    Q_ACTION_CAST(&Calc_operand_frac_ep), /* EP */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_clear();
            BSP_insert((int)'0');
            BSP_insert((int)'.');
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::ready::OPER} */
        case OPER_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_opEntered_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_ready_x), /* exit */
                    Q_ACTION_CAST(&Calc_opEntered_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            me->op1 = BSP_get_value();
            me->oper1 = Q_EVT_CAST(CalcEvt)->key_code;
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*.${SMs::Calc::SM::on::ready::result} .....................................*/
QMState const Calc_result_s = {
    &Calc_ready_s, /* superstate */
    Q_STATE_CAST(&Calc_result),
    Q_ACTION_CAST(&Calc_result_e),
    Q_ACTION_CAST(&Calc_result_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::on::ready::result} */
QState Calc_result_e(Calc * const me) {
    BSP_message("result-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_result_s);
}
/*.${SMs::Calc::SM::on::ready::result} */
QState Calc_result_x(Calc * const me) {
    BSP_message("result-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_result_s);
}
/*.${SMs::Calc::SM::on::ready::result} */
QState Calc_result(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.${SMs::Calc::SM::on::ready::begin} ......................................*/
QMState const Calc_begin_s = {
    &Calc_ready_s, /* superstate */
    Q_STATE_CAST(&Calc_begin),
    Q_ACTION_CAST(&Calc_begin_e),
    Q_ACTION_CAST(&Calc_begin_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::on::ready::begin} */
QState Calc_begin_e(Calc * const me) {
    BSP_message("begin-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_begin_s);
}
/*.${SMs::Calc::SM::on::ready::begin} */
QState Calc_begin_x(Calc * const me) {
    BSP_message("begin-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_begin_s);
}
/*.${SMs::Calc::SM::on::ready::begin} */
QState Calc_begin(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::on::ready::begin::OPER} */
        case OPER_SIG: {
            /*.${SMs::Calc::SM::on::ready::begin::OPER::[e->key=='-']} */
            if (Q_EVT_CAST(CalcEvt)->key_code == KEY_MINUS) {
                static struct {
                    QMState const *target;
                    QActionHandler act[5];
                } const tatbl_ = { /* tran-action table */
                    &Calc_operand_s, /* target submachine */
                    {
                        Q_ACTION_CAST(&Calc_begin_x), /* exit */
                        Q_ACTION_CAST(&Calc_ready_x), /* exit */
                        Q_ACTION_CAST(&Calc_operand1_e), /* entry */
                        Q_ACTION_CAST(&Calc_operand_neg_ep), /* EP */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN_EP(&tatbl_);
            }
            /*.${SMs::Calc::SM::on::ready::begin::OPER::[else]} */
            else {
                status_ = QM_HANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.${SMs::Calc::SM::on::opEntered} .........................................*/
QMState const Calc_opEntered_s = {
    &Calc_on_s, /* superstate */
    Q_STATE_CAST(&Calc_opEntered),
    Q_ACTION_CAST(&Calc_opEntered_e),
    Q_ACTION_CAST(&Calc_opEntered_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::on::opEntered} */
QState Calc_opEntered_e(Calc * const me) {
    BSP_message("opEntered-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_opEntered_s);
}
/*.${SMs::Calc::SM::on::opEntered} */
QState Calc_opEntered_x(Calc * const me) {
    BSP_message("opEntered-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_opEntered_s);
}
/*.${SMs::Calc::SM::on::opEntered} */
QState Calc_opEntered(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::on::opEntered::DIGIT_0} */
        case DIGIT_0_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_CAST(&Calc_opEntered_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand2_e), /* entry */
                    Q_ACTION_CAST(&Calc_operand_zero_ep), /* EP */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_clear();
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::opEntered::DIGIT_1_9} */
        case DIGIT_1_9_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_CAST(&Calc_opEntered_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand2_e), /* entry */
                    Q_ACTION_CAST(&Calc_operand_intgr_ep), /* EP */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_clear();
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::opEntered::POINT} */
        case POINT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_CAST(&Calc_opEntered_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand2_e), /* entry */
                    Q_ACTION_CAST(&Calc_operand_frac_ep), /* EP */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_clear();
            BSP_insert((int)'0');
            BSP_insert((int)'.');
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::opEntered::OPER} */
        case OPER_SIG: {
            /*.${SMs::Calc::SM::on::opEntered::OPER::[e->key=='-']} */
            if (Q_EVT_CAST(CalcEvt)->key_code == KEY_MINUS) {
                static struct {
                    QMState const *target;
                    QActionHandler act[4];
                } const tatbl_ = { /* tran-action table */
                    &Calc_operand_s, /* target submachine */
                    {
                        Q_ACTION_CAST(&Calc_opEntered_x), /* exit */
                        Q_ACTION_CAST(&Calc_operand2_e), /* entry */
                        Q_ACTION_CAST(&Calc_operand_neg_ep), /* EP */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN_EP(&tatbl_);
            }
            /*.${SMs::Calc::SM::on::opEntered::OPER::[else]} */
            else {
                status_ = QM_HANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.${SMs::Calc::SM::on::operand1} ..........................................*/
struct SM_operand const Calc_operand1_s = {
    {
        &Calc_on_s, /* superstate */
        Q_STATE_CAST(&Calc_operand1),
        Q_ACTION_CAST(&Calc_operand1_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&Calc_operand1_ce)
};
/*.${SMs::Calc::SM::on::operand1} */
QState Calc_operand1_e(Calc * const me) {
    me->sub_operand = &Calc_operand1_s; /* attach submachine */
    return Calc_operand_e(me); /* enter submachine */
}
/*.${SMs::Calc::SM::on::operand1} */
QState Calc_operand1_ce(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[4];
    } const tatbl_ = { /* tran-action table */
        &Calc_ready_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_operand_x), /* submachine exit */
            Q_ACTION_CAST(&Calc_ready_e), /* entry */
            Q_ACTION_CAST(&Calc_ready_i), /* initial tran. */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    BSP_clear();
    return QM_TRAN(&tatbl_);
}
/*.${SMs::Calc::SM::on::operand1} */
QState Calc_operand1(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::on::operand1::EQUALS} */
        case EQUALS_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_result_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_ready_e), /* entry */
                    Q_ACTION_CAST(&Calc_result_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::on::operand1::OPER} */
        case OPER_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { /* tran-action table */
                &Calc_opEntered_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_opEntered_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            me->op1 = BSP_get_value();
            me->oper1 = Q_EVT_CAST(CalcEvt)->key_code;
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*.${SMs::Calc::SM::on::operand2} ..........................................*/
struct SM_operand const Calc_operand2_s = {
    {
        &Calc_on_s, /* superstate */
        Q_STATE_CAST(&Calc_operand2),
        Q_ACTION_CAST(&Calc_operand2_e),
        Q_ACTION_NULL, /* no exit action */
        Q_ACTION_NULL  /* no initial tran. */
    }
    ,Q_ACTION_CAST(&Calc_operand2_ce)
};
/*.${SMs::Calc::SM::on::operand2} */
QState Calc_operand2_e(Calc * const me) {
    me->sub_operand = &Calc_operand2_s; /* attach submachine */
    return Calc_operand_e(me); /* enter submachine */
}
/*.${SMs::Calc::SM::on::operand2} */
QState Calc_operand2_ce(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[3];
    } const tatbl_ = { /* tran-action table */
        &Calc_opEntered_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_operand_x), /* submachine exit */
            Q_ACTION_CAST(&Calc_opEntered_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    (void)me; /* unused parameter */
    BSP_clear();
    return QM_TRAN(&tatbl_);
}
/*.${SMs::Calc::SM::on::operand2} */
QState Calc_operand2(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::on::operand2::OPER} */
        case OPER_SIG: {
            /*.${SMs::Calc::SM::on::operand2::OPER::[Calc_eval(me,BSP_get_value(),Q_~} */
            if (Calc_eval(me, BSP_get_value(), Q_EVT_CAST(CalcEvt)->key_code)) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* tran-action table */
                    &Calc_opEntered_s, /* target state */
                    {
                        Q_ACTION_CAST(&Calc_opEntered_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            /*.${SMs::Calc::SM::on::operand2::OPER::[else]} */
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* tran-action table */
                    &Calc_error_s, /* target state */
                    {
                        Q_ACTION_CAST(&Calc_error_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        /*.${SMs::Calc::SM::on::operand2::EQUALS} */
        case EQUALS_SIG: {
            /*.${SMs::Calc::SM::on::operand2::EQUALS::[Calc_eval(me,BSP_get_value(),KE~} */
            if (Calc_eval(me, BSP_get_value(), KEY_NULL)
)
            {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { /* tran-action table */
                    &Calc_result_s, /* target state */
                    {
                        Q_ACTION_CAST(&Calc_ready_e), /* entry */
                        Q_ACTION_CAST(&Calc_result_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            /*.${SMs::Calc::SM::on::operand2::EQUALS::[else]} */
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { /* tran-action table */
                    &Calc_error_s, /* target state */
                    {
                        Q_ACTION_CAST(&Calc_error_e), /* entry */
                        Q_ACTION_NULL /* zero terminator */
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*.$enddef${SMs::Calc::SM::on} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${SMs::Calc::SM::final} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::Calc::SM::final} .................................................*/
QMState const Calc_final_s = {
    QM_STATE_NULL, /* superstate (top) */
    Q_STATE_CAST(&Calc_final),
    Q_ACTION_CAST(&Calc_final_e),
    Q_ACTION_NULL, /* no exit action */
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::final} */
QState Calc_final_e(Calc * const me) {
    BSP_message("final-ENTRY;");
    BSP_exit();
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_final_s);
}
/*.${SMs::Calc::SM::final} */
QState Calc_final(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.$enddef${SMs::Calc::SM::final} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
