/*.$file${.::calc1_sub1.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: calc1_sub1.qm
* File:  ${.::calc1_sub1.c}
*
* This code has been generated by QM 4.6.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This code is covered by the following QP license:
* License #   : QPC-EVAL
* Issued to   : Institution or an individual evaluating the QP/C framework
* Framework(s): qpc
* Support ends: 2020-12-31
* Product(s)  :
* This license is available only for evaluation purposes and
* the generated code is still licensed under the terms of GPL.
* Please submit request for extension of the evaluaion period at:
* https://www.state-machine.com/licensing/#RequestForm
*/
/*.$endhead${.::calc1_sub1.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"   /* QP/C */
#include "bsp.h"   /* board support package */
#include "calc1.h" /* application */

/*.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*. Check for the minimum required QP version */
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.5.0 or higher required
#endif
/*.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*.$define${SMs::Calc::SM::operand} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${SMs::Calc::SM::operand} ...............................................*/
/*.${SMs::Calc::SM::operand} */
QMState const Calc_operand_s = {
    QM_STATE_NULL, /* superstate unused */
    Q_STATE_CAST(&Calc_operand),
    Q_ACTION_CAST(&Calc_operand_e),
    Q_ACTION_CAST(&Calc_operand_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::operand} */
QState Calc_operand_e(Calc * const me) {
    BSP_message("operand-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_operand_s);
}
/*.${SMs::Calc::SM::operand} */
QState Calc_operand_x(Calc * const me) {
    BSP_message("operand-EXIT;");
    return QM_SM_EXIT(&me->sub_operand->super);
}
/*.${SMs::Calc::SM::operand} */
QState Calc_operand(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::operand::CE} */
        case CE_SIG: {
            static QMTranActTable const tatbl_ = { /* tran-action table */
                &Calc_operand_s, /* target submachine */
                {
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            status_ = QM_TRAN_XP(me->sub_operand->ce, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER_SUB(&me->sub_operand->super);
            break;
        }
    }
    return status_;
}
/*.${SMs::Calc::SM::operand::EP-zero} */
QState Calc_operand_zero_ep(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &Calc_operand_zero_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_operand_zero_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*.${SMs::Calc::SM::operand::EP-intgr} */
QState Calc_operand_intgr_ep(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &Calc_operand_int_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_operand_int_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*.${SMs::Calc::SM::operand::EP-frac} */
QState Calc_operand_frac_ep(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &Calc_operand_frac_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_operand_frac_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*.${SMs::Calc::SM::operand::EP-neg} */
QState Calc_operand_neg_ep(Calc * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { /* tran-action table */
        &Calc_operand_negated_s, /* target state */
        {
            Q_ACTION_CAST(&Calc_operand_negated_e), /* entry */
            Q_ACTION_NULL /* zero terminator */
        }
    };
    return QM_TRAN_EP(&tatbl_);
}
/*.${SMs::Calc::SM::operand::zero} .........................................*/
QMState const Calc_operand_zero_s = {
    &Calc_operand_s, /* superstate */
    Q_STATE_CAST(&Calc_operand_zero),
    Q_ACTION_CAST(&Calc_operand_zero_e),
    Q_ACTION_CAST(&Calc_operand_zero_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::operand::zero} */
QState Calc_operand_zero_e(Calc * const me) {
    BSP_message("zero-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_operand_zero_s);
}
/*.${SMs::Calc::SM::operand::zero} */
QState Calc_operand_zero_x(Calc * const me) {
    BSP_message("zero-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_operand_zero_s);
}
/*.${SMs::Calc::SM::operand::zero} */
QState Calc_operand_zero(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::operand::zero::DIGIT_0} */
        case DIGIT_0_SIG: {
            ;
            status_ = QM_HANDLED();
            break;
        }
        /*.${SMs::Calc::SM::operand::zero::DIGIT_1_9} */
        case DIGIT_1_9_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_int_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_operand_zero_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand_int_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::operand::zero::POINT} */
        case POINT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_frac_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_operand_zero_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand_frac_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_insert((int)'0');
            BSP_insert((int)'.');
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/*.${SMs::Calc::SM::operand::int} ..........................................*/
QMState const Calc_operand_int_s = {
    &Calc_operand_s, /* superstate */
    Q_STATE_CAST(&Calc_operand_int),
    Q_ACTION_CAST(&Calc_operand_int_e),
    Q_ACTION_CAST(&Calc_operand_int_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::operand::int} */
QState Calc_operand_int_e(Calc * const me) {
    BSP_message("int-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_operand_int_s);
}
/*.${SMs::Calc::SM::operand::int} */
QState Calc_operand_int_x(Calc * const me) {
    BSP_message("int-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_operand_int_s);
}
/*.${SMs::Calc::SM::operand::int} */
QState Calc_operand_int(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::operand::int::POINT} */
        case POINT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_frac_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_operand_int_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand_frac_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_insert((int)'.');
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::operand::int::DIGIT_0, DIGIT_1_9} */
        case DIGIT_0_SIG: /* intentionally fall through */
        case DIGIT_1_9_SIG: {
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.${SMs::Calc::SM::operand::frac} .........................................*/
QMState const Calc_operand_frac_s = {
    &Calc_operand_s, /* superstate */
    Q_STATE_CAST(&Calc_operand_frac),
    Q_ACTION_CAST(&Calc_operand_frac_e),
    Q_ACTION_CAST(&Calc_operand_frac_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::operand::frac} */
QState Calc_operand_frac_e(Calc * const me) {
    BSP_message("frac-ENTRY;");
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_operand_frac_s);
}
/*.${SMs::Calc::SM::operand::frac} */
QState Calc_operand_frac_x(Calc * const me) {
    BSP_message("frac-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_operand_frac_s);
}
/*.${SMs::Calc::SM::operand::frac} */
QState Calc_operand_frac(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::operand::frac::POINT} */
        case POINT_SIG: {
            ;
            status_ = QM_HANDLED();
            break;
        }
        /*.${SMs::Calc::SM::operand::frac::DIGIT_0, DIGIT_1_9} */
        case DIGIT_0_SIG: /* intentionally fall through */
        case DIGIT_1_9_SIG: {
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.${SMs::Calc::SM::operand::negated} ......................................*/
QMState const Calc_operand_negated_s = {
    &Calc_operand_s, /* superstate */
    Q_STATE_CAST(&Calc_operand_negated),
    Q_ACTION_CAST(&Calc_operand_negated_e),
    Q_ACTION_CAST(&Calc_operand_negated_x),
    Q_ACTION_NULL  /* no initial tran. */
};
/*.${SMs::Calc::SM::operand::negated} */
QState Calc_operand_negated_e(Calc * const me) {
    BSP_message("negated-ENTRY;");
    BSP_negate();
    (void)me; /* unused parameter */
    return QM_ENTRY(&Calc_operand_negated_s);
}
/*.${SMs::Calc::SM::operand::negated} */
QState Calc_operand_negated_x(Calc * const me) {
    BSP_message("negated-EXIT;");
    (void)me; /* unused parameter */
    return QM_EXIT(&Calc_operand_negated_s);
}
/*.${SMs::Calc::SM::operand::negated} */
QState Calc_operand_negated(Calc * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*.${SMs::Calc::SM::operand::negated::DIGIT_0} */
        case DIGIT_0_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_zero_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_operand_negated_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand_zero_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::operand::negated::DIGIT_1_9} */
        case DIGIT_1_9_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_int_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_operand_negated_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand_int_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::operand::negated::POINT} */
        case POINT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { /* tran-action table */
                &Calc_operand_frac_s, /* target state */
                {
                    Q_ACTION_CAST(&Calc_operand_negated_x), /* exit */
                    Q_ACTION_CAST(&Calc_operand_frac_e), /* entry */
                    Q_ACTION_NULL /* zero terminator */
                }
            };
            BSP_insert(Q_EVT_CAST(CalcEvt)->key_code);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        /*.${SMs::Calc::SM::operand::negated::OPER} */
        case OPER_SIG: {
            /*.${SMs::Calc::SM::operand::negated::OPER::[e->key=='-']} */
            if (Q_EVT_CAST(CalcEvt)->key_code == KEY_MINUS) {
                ;
                status_ = QM_HANDLED();
            }
            /*.${SMs::Calc::SM::operand::negated::OPER::[else]} */
            else {
                status_ = QM_HANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    (void)me; /* unused parameter */
    return status_;
}
/*.$enddef${SMs::Calc::SM::operand} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
